version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=desafio
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=desafio
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 5


# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#     ports:
#       - '3001:3001'
#     environment:
#       - DB_HOST=db
#       - DB_USER=postgres
#       - DB_PASSWORD=password
#       - DB_NAME=desafio
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=desafio
#     ports:
#       - '5432:5432'
